import { Inter } from 'next/font/google';
import NavBar from '@/components/navbar';
import './globals.css';
import { ReduxProvider } from '@/Redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'BookStore',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <ReduxProvider>
          <NavBar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
